/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thon;

/**
 *
 * @author Gisward
 */
public class MainMenuUI extends javax.swing.JFrame 
{
    private NavigationCntl parentNavigationCntl;
    
    public MainMenuUI(NavigationCntl newParentNavigationCntl) {
        this.parentNavigationCntl = newParentNavigationCntl;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * 
     * initComponents() creates the JFrame's components (radioButton Group,
     * radio buttons, labels, and text fields), it sets up the components (sets text,
     * sets font, sets the size, and adds an action listener to a component if specified
     * from the Java GUI)
     * 
     * For the radioButton group, it adds all the radio buttons to the button group
     * so that only one radio button can be chosen at a time
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButtonGroup = new javax.swing.ButtonGroup();
        spaceAssignRadioButton = new javax.swing.JRadioButton();
        currentCapacityRadioButton = new javax.swing.JRadioButton();
        thonraiserRadioButton = new javax.swing.JRadioButton();
        thonpassRadioButton = new javax.swing.JRadioButton();
        userIconLabel = new javax.swing.JLabel();
        userTextField = new javax.swing.JTextField();
        chooseLabel = new javax.swing.JLabel();
        userTitleLabel = new javax.swing.JLabel();
        tcsLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        goButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        radioButtonGroup.add(spaceAssignRadioButton);
        spaceAssignRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        spaceAssignRadioButton.setText("Space Assignment");
        spaceAssignRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spaceAssignRadioButtonActionPerformed(evt);
            }
        });

        radioButtonGroup.add(currentCapacityRadioButton);
        currentCapacityRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        currentCapacityRadioButton.setText("Current THON Capacity");

        radioButtonGroup.add(thonraiserRadioButton);
        thonraiserRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        thonraiserRadioButton.setText("THONraiser");

        radioButtonGroup.add(thonpassRadioButton);
        thonpassRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        thonpassRadioButton.setText("THONPass");

        userIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thon/myimage/user-alt-128.png"))); // NOI18N

        userTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userTextField.setText(parentNavigationCntl.getUsername());
        userTextField.setBorder(null);
        userTextField.setEditable(false);
        userTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTextFieldActionPerformed(evt);
            }
        });

        chooseLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chooseLabel.setText("Choose one of the following: ");

        userTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userTitleLabel.setText("User:");

        tcsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thon/myimage/THONLogo.png"))); // NOI18N

        exitButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        goButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        goButton.setText("Go");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(userTextField)
                                .addComponent(userIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(userTitleLabel))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spaceAssignRadioButton)
                            .addComponent(currentCapacityRadioButton)
                            .addComponent(thonpassRadioButton)
                            .addComponent(thonraiserRadioButton)
                            .addComponent(chooseLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(tcsLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(exitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(goButton)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(tcsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userTitleLabel)
                    .addComponent(chooseLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exitButton)
                            .addComponent(goButton))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spaceAssignRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(currentCapacityRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(thonpassRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(thonraiserRadioButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(userIconLabel)
                                .addGap(1, 1, 1)
                                .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(71, 71, 71))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // userTextFieldActionPerformed() not used
    private void userTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTextFieldActionPerformed

    }//GEN-LAST:event_userTextFieldActionPerformed
    
    // spaceAssignRadioButtonActionPerformed() not used
    private void spaceAssignRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spaceAssignRadioButtonActionPerformed

    }//GEN-LAST:event_spaceAssignRadioButtonActionPerformed

    // exitButtonActionPerformed() calls System.exit command which ends the program
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * goButtonActionPerformed(): deals with all the user-entered menu options.
     * It takes an ActionEvent object as a parameter (so basically if go is clicked,
     * then it evaluates where to send the user based on which radio button was 
     * selected, as seen by the boolean variables for each of the 4 menu options
     * 
     * using if-else if-else statements to evaluate the value of each boolean, the user
     * will be taken to each menu option's respective controller (i.e, SpaceAssignCntl 
     * for the spaceAssignRadioButton)
     * 
     * @param evt 
     */
    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        
        boolean spaceAssignSelected = spaceAssignRadioButton.isSelected();
        boolean currentCapacitySelected = currentCapacityRadioButton.isSelected();
        boolean thonpassSelected = thonpassRadioButton.isSelected();
        boolean thonraiserSelected = thonraiserRadioButton.isSelected();
        
        if(spaceAssignSelected == true)
        {
            this.setVisible(false);
            parentNavigationCntl.requestSpaceAssignCntl();
        }
        else if(currentCapacitySelected == true)
        {
            
        }
        else if(thonpassSelected == true)
        {
            
        }
        else if(thonraiserSelected == true)
        {
            
        }
        else
        {
            System.err.println("Choose a menu option.");
        }
    }//GEN-LAST:event_goButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MainMenuUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chooseLabel;
    private javax.swing.JRadioButton currentCapacityRadioButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton goButton;
    private javax.swing.ButtonGroup radioButtonGroup;
    private javax.swing.JRadioButton spaceAssignRadioButton;
    private javax.swing.JLabel tcsLabel;
    private javax.swing.JRadioButton thonpassRadioButton;
    private javax.swing.JRadioButton thonraiserRadioButton;
    private javax.swing.JLabel userIconLabel;
    private javax.swing.JTextField userTextField;
    private javax.swing.JLabel userTitleLabel;
    // End of variables declaration//GEN-END:variables
}
